-- MySQL Script generated by MySQL Workbench
-- Fri Nov  2 14:55:12 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema producciones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema producciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `producciones` DEFAULT CHARACTER SET utf8 ;
USE `producciones` ;

-- -----------------------------------------------------
-- Table `producciones`.`TBL_Prioridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `producciones`.`TBL_Prioridad` (
  `idTBL_Prioridad` INT NOT NULL,
  `descripcion_Prioridad` VARCHAR(45) NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`idTBL_Prioridad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `producciones`.`TBL_Operacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `producciones`.`TBL_Operacion` (
  `idTBL_Operacion` INT NOT NULL,
  `Descripcion` VARCHAR(100) NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`idTBL_Operacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `producciones`.`TBL_Estado_Avance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `producciones`.`TBL_Estado_Avance` (
  `idTBL_Estado_Avance` INT NOT NULL,
  `Estado_Avance` VARCHAR(45) NULL,
  `Fecha_ultimoMov` DATE NULL,
  `TBL_Operacion_idTBL_Operacion` INT NOT NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`idTBL_Estado_Avance`, `TBL_Operacion_idTBL_Operacion`),
  INDEX `fk_TBL_Estado_Avance_TBL_Operación1_idx` (`TBL_Operacion_idTBL_Operacion` ASC),
  CONSTRAINT `fk_TBL_Estado_Avance_TBL_Operación1`
    FOREIGN KEY (`TBL_Operacion_idTBL_Operacion`)
    REFERENCES `producciones`.`TBL_Operacion` (`idTBL_Operacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `producciones`.`TBL_Orden_Produccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `producciones`.`TBL_Orden_Produccion` (
  `idTBL_Orden_Produccion` INT NOT NULL,
  `Creador_orden` VARCHAR(45) NULL,
  `Fecha_Inicio` DATE NULL,
  `Fecha_Finalizacion` DATE NULL,
  `TBL_Prioridad_idTBL_Prioridad` INT NOT NULL,
  `TBL_Estado_Avance_idTBL_Estado_Avance` INT NOT NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`idTBL_Orden_Produccion`, `TBL_Prioridad_idTBL_Prioridad`, `TBL_Estado_Avance_idTBL_Estado_Avance`),
  INDEX `fk_TBL_Orden_Produccion_TBL_Prioridad1_idx` (`TBL_Prioridad_idTBL_Prioridad` ASC),
  INDEX `fk_TBL_Orden_Produccion_TBL_Estado_Avance1_idx` (`TBL_Estado_Avance_idTBL_Estado_Avance` ASC),
  CONSTRAINT `fk_TBL_Orden_Produccion_TBL_Prioridad1`
    FOREIGN KEY (`TBL_Prioridad_idTBL_Prioridad`)
    REFERENCES `producciones`.`TBL_Prioridad` (`idTBL_Prioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Orden_Produccion_TBL_Estado_Avance1`
    FOREIGN KEY (`TBL_Estado_Avance_idTBL_Estado_Avance`)
    REFERENCES `producciones`.`TBL_Estado_Avance` (`idTBL_Estado_Avance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `producciones`.`TBL_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `producciones`.`TBL_Producto` (
  `PK_Codigo_Producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_Codigo_Producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `producciones`.`TBL_Explosion_Materiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `producciones`.`TBL_Explosion_Materiales` (
  `idTBL_Explosion_Materiales` INT NOT NULL,
  `Cantidad_prod` FLOAT NULL,
  `Status` TINYINT(1) NULL,
  `Faltante` FLOAT NULL,
  `pk_codigo_producto` INT NOT NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`idTBL_Explosion_Materiales`),
  INDEX `fk_TBL_Explosion_Materiales_TBL_Producto1_idx` (`pk_codigo_producto` ASC),
  CONSTRAINT `fk_TBL_Explosion_Materiales_TBL_Producto1`
    FOREIGN KEY (`pk_codigo_producto`)
    REFERENCES `producciones`.`TBL_Producto` (`PK_Codigo_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `producciones`.`TBL_Orden_Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `producciones`.`TBL_Orden_Detalle` (
  `idTBL_Orden_Detalle` INT NOT NULL,
  `TBL_Orden_Produccion_idTBL_Orden_Produccion` INT NOT NULL,
  `TBL_Producto_pk_codigo_producto` INT NOT NULL,
  `Cantidad_prod` FLOAT NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`idTBL_Orden_Detalle`, `TBL_Orden_Produccion_idTBL_Orden_Produccion`, `TBL_Producto_pk_codigo_producto`),
  INDEX `fk_TBL_Orden_Detalle_TBL_Orden_Produccion1_idx` (`TBL_Orden_Produccion_idTBL_Orden_Produccion` ASC),
  INDEX `fk_TBL_Orden_Detalle_TBL_Producto1_idx` (`TBL_Producto_pk_codigo_producto` ASC),
  CONSTRAINT `fk_TBL_Orden_Detalle_TBL_Orden_Produccion1`
    FOREIGN KEY (`TBL_Orden_Produccion_idTBL_Orden_Produccion`)
    REFERENCES `producciones`.`TBL_Orden_Produccion` (`idTBL_Orden_Produccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Orden_Detalle_TBL_Producto1`
    FOREIGN KEY (`TBL_Producto_pk_codigo_producto`)
    REFERENCES `producciones`.`TBL_Producto` (`PK_Codigo_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
