-- MySQL Script generated by MySQL Workbench
-- Mon Oct 22 18:45:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ordenes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ordenes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ordenes` DEFAULT CHARACTER SET utf8 ;
USE `ordenes` ;

-- -----------------------------------------------------
-- Table `ordenes`.`TBL_Lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordenes`.`TBL_Lote` (
  `idTBL_Lote` INT NOT NULL,
  `No_Lote` INT NULL,
  `Estatus` INT NULL,
  PRIMARY KEY (`idTBL_Lote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordenes`.`TBL_Linea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordenes`.`TBL_Linea` (
  `idTBL_Linea` INT NOT NULL,
  `descripcion_Linea` VARCHAR(45) NULL,
  `Estatus` INT NULL,
  PRIMARY KEY (`idTBL_Linea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordenes`.`TBL_Estado_Avance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordenes`.`TBL_Estado_Avance` (
  `idTBL_Estado_Avance` INT NOT NULL,
  `Estado_Avance` VARCHAR(45) NULL,
  `Fecha_ultimoMov` DATE NULL,
  `TBL_Linea_idTBL_Linea` INT NOT NULL,
  `Estatus` INT NULL,
  PRIMARY KEY (`idTBL_Estado_Avance`),
  INDEX `fk_TBL_Estado_Avane_TBL_Linea1_idx` (`TBL_Linea_idTBL_Linea` ASC),
  CONSTRAINT `fk_TBL_Estado_Avane_TBL_Linea1`
    FOREIGN KEY (`TBL_Linea_idTBL_Linea`)
    REFERENCES `ordenes`.`TBL_Linea` (`idTBL_Linea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordenes`.`TBL_Prioridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordenes`.`TBL_Prioridad` (
  `idTBL_Prioridad` INT NOT NULL,
  `descripcion_Prioridad` VARCHAR(45) NULL,
  `Estatus` INT NULL,
  PRIMARY KEY (`idTBL_Prioridad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordenes`.`TBL_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordenes`.`TBL_Producto` (
  `idTBL_Producto` INT NOT NULL,
  `descripcion_Producto` VARCHAR(45) NULL,
  `Existencia_producto` INT NULL,
  `Estatus` INT NULL,
  PRIMARY KEY (`idTBL_Producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordenes`.`TBL_Orden_Produccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordenes`.`TBL_Orden_Produccion` (
  `idTBL_Orden_Produccion` INT NOT NULL,
  `Cantidad_Producto` INT NULL,
  `Fecha_Inicio` DATE NULL,
  `TBL_Lote_idTBL_Lote` INT NOT NULL,
  `TBL_Estado_Avane_idTBL_Estado_Avane` INT NOT NULL,
  `TBL_Prioridad_idTBL_Prioridad` INT NOT NULL,
  `TBL_Producto_idTBL_Producto` INT NOT NULL,
  `Estatus` INT NULL,
  PRIMARY KEY (`idTBL_Orden_Produccion`),
  INDEX `fk_TBL_Orden_Producción_TBL_Lote_idx` (`TBL_Lote_idTBL_Lote` ASC),
  INDEX `fk_TBL_Orden_Producción_TBL_Estado_Avane1_idx` (`TBL_Estado_Avane_idTBL_Estado_Avane` ASC),
  INDEX `fk_TBL_Orden_Producción_TBL_Prioridad1_idx` (`TBL_Prioridad_idTBL_Prioridad` ASC),
  INDEX `fk_TBL_Orden_Producción_TBL_Producto1_idx` (`TBL_Producto_idTBL_Producto` ASC),
  CONSTRAINT `fk_TBL_Orden_Producción_TBL_Lote`
    FOREIGN KEY (`TBL_Lote_idTBL_Lote`)
    REFERENCES `ordenes`.`TBL_Lote` (`idTBL_Lote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Orden_Producción_TBL_Estado_Avane1`
    FOREIGN KEY (`TBL_Estado_Avane_idTBL_Estado_Avane`)
    REFERENCES `ordenes`.`TBL_Estado_Avance` (`idTBL_Estado_Avance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Orden_Producción_TBL_Prioridad1`
    FOREIGN KEY (`TBL_Prioridad_idTBL_Prioridad`)
    REFERENCES `ordenes`.`TBL_Prioridad` (`idTBL_Prioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Orden_Producción_TBL_Producto1`
    FOREIGN KEY (`TBL_Producto_idTBL_Producto`)
    REFERENCES `ordenes`.`TBL_Producto` (`idTBL_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
